### ISSUE TITLE
Path for default sound files

### ISSUE THREAD

**Issue by osworx** [mahkassem/mk-notifications#2]
Currently the default sound files are hard coded inside the js:
`var defaultSound = './src/sound/notification.mp3',
	defaultClose = './src/sound/close.mp3';`
That assumes that these files cannot be stored in a custom folder deeper than 1 folder below root.
Which is basically limiting the usage.

Maybe reworking this to define only the soundfiles itself and hand over the path via options?
For example:
`var defaultSound = 'notification.mp3',
	defaultClose = 'close.mp3';`
And via the function something like:
`soundPath: 'my/custom/path/to/the/sound/',`
and inside the .js something like:
`soundPath: mkOptions.soundPath != undefined ? mkOptions.soundPath : ''`

**Comment by mahkassem** [comment]
The default sound can be replaced with custom sounds as following:

```
sound: true,
customSound: {
    onShow: "./src/sound/custom-notification.mp3",
    onClose: "./src/sound/custom-close.mp3"
}
```


you can add this as a variable in your global variable sounds as following:

```
var defaultSound = {
        onShow: "./src/sound/default-notification.mp3",
        onClose: "./src/sound/default-close.mp3"
    };

var altSound = {
        onShow: "./src/sound/custom-notification.mp3",
        onClose: "./src/sound/custom-close.mp3"
    };
```
Then you can use it like so: 

```
var options = 
{
    sound: true,
    customSound: defaultSound
};

mkNoti(
    "MK Web Notifications",
    "Example of generated notification with Notifications Generator",
    options
);
```
You can also create multiple options variables and use them with _mkNoti()_ function directly:


```
var altOptions = 
{
    sound: true,
    customSound: altSound
};

mkNoti(
    "MK Web Notifications",
    "Example of generated notification with Notifications Generator",
    altOptions
);
```
